package edu.cmu.square.server.dao.model;

// Generated May 17, 2009 5:07:01 PM by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import edu.cmu.square.client.model.GwtArtifact;

/**
 * Artifact generated by hbm2java
 */
@Entity
@Table(name = "artifact")
public class Artifact implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 8156900348242740110L;
	private Integer id;
	private Project project;
	private String name;
	private String description;
	private String revision;
	private String link;
	private Date dateCreated;
	private Date dateModified;
	private Set<Risk> risks = new HashSet<Risk>(0);
	
	
	public Artifact()
	{
	
	}

	public Artifact(Project project, String name, String description, String artifactVersion, String link)
	{
		this.project = project;
		this.name= name;
		this.description = description;
		this.revision = artifactVersion;
		this.link = link;
	}
	
	public Artifact(Project project,String name, String description, String artifactVersion, String link, Date dateCreated, Date dateModified)
	{
		this.project = project;
		this.name=name;
		this.description = description;
		this.revision = artifactVersion;
		this.link = link;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
	}

	public Artifact(GwtArtifact gwtArtifact)
	{
		this.id = gwtArtifact.getId();
		this.name = gwtArtifact.getName();
		this.description = gwtArtifact.getDescription();
		this.link = gwtArtifact.getLink();
		this.revision = gwtArtifact.getRevision();
	}

	
	
	public GwtArtifact createGwtArtifact()
	{
		GwtArtifact gwtArtifact = new GwtArtifact();
		gwtArtifact.setId(this.id);
		gwtArtifact.setName(this.name);
		gwtArtifact.setDescription(this.description);
		gwtArtifact.setRevision(this.revision);
		gwtArtifact.setLink(this.link);
		return gwtArtifact;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pid", nullable = false)
	public Project getProject()
	{
		return this.project;
	}

	public void setProject(Project project)
	{
		this.project = project;
	}
	@Column(name = "name", nullable = false, length = 65535)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription()
	{
		return this.description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}

	@Column(name = "artifact_version", nullable = false, length = 65535)
	public String getRevision()
	{
		return this.revision;
	}

	public void setRevision(String revision)
	{
		this.revision = revision;
	}

	@Column(name = "link", nullable = false, length = 65535)
	public String getLink()
	{
		return this.link;
	}

	public void setLink(String link)
	{
		this.link = link;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_created", nullable = true, length = 19)
	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_modified", nullable = false, length = 19)
	public Date getDateModified()
	{
		return this.dateModified;
	}

	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

	@ManyToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, mappedBy = "artifacts", targetEntity = Risk.class)
	public Set<Risk> getRisks()
	{
		return risks;
	}

	public void setRisks(Set<Risk> risks)
	{
		this.risks = risks;
	}



}
