package edu.cmu.square.server.dao.model;

// Generated May 17, 2009 5:07:01 PM by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import edu.cmu.square.client.model.GwtEvaluation;

/**
 * TechniqueEvaluation generated by hbm2java
 */
@Entity
@Table(name = "evaluation_criteria")
public class EvaluationCriteria implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2466214878246048973L;
	private Integer id;
	private String name;
	private String description;
	
	private Date dateCreated;
	private Date dateModified;
	private Project project;

	public EvaluationCriteria() {
	}
	
	public EvaluationCriteria(GwtEvaluation gwtEvaluation){
		this.id = gwtEvaluation.getEvaluationId();
		this.name = gwtEvaluation.getTitle();
		this.description = gwtEvaluation.getDescription();
	}

	public EvaluationCriteria(String name, String description,
			Date dateCreated, Date dateModified) {
		this.name = name;
		this.description = description;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
	}

	

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_created", nullable = false, length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_modified", nullable = false, length = 19)
	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	

	public GwtEvaluation createGwtTechnique() {
		GwtEvaluation gwtEvaluation = new GwtEvaluation();
		gwtEvaluation.setTitle(this.name);
		gwtEvaluation.setDescription(this.description);
		gwtEvaluation.setEvaluationId(this.id);
		return gwtEvaluation;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

}
