package edu.cmu.square.server.dao.model;

// Generated May 17, 2009 5:07:01 PM by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import edu.cmu.square.client.model.GwtAsset;
import edu.cmu.square.client.model.GwtSubGoal;

/**
 * Goal generated by hbm2java
 */
@Entity
@Table(name = "goal")
public class Goal implements java.io.Serializable
{

	private static final long serialVersionUID = 6196573734792678634L;
	private Integer id;
	private GoalType goalType;
	private Project project;
	private Set<Asset> assets = new HashSet<Asset>(0);
	private String description;
	private int priority;
	private Date dateCreated;
	private Date dateModified;

	public Goal()
		{
		}

	public Goal(GoalType goalType, Project project, String description, int priority, Date dateCreated, Date dateModified)
		{
			this.goalType = goalType;
			this.project = project;
			this.description = description;
			this.priority = priority;
			this.dateCreated = dateCreated;
			this.dateModified = dateModified;
		}

	public Goal(GwtSubGoal subGoal)
		{
			this.id = subGoal.getId();
			this.description = subGoal.getDescription();
			this.priority = subGoal.getPriority();
		}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type", nullable = false)
	public GoalType getGoalType()
	{
		return this.goalType;
	}

	public void setGoalType(GoalType goalType)
	{
		this.goalType = goalType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pid", nullable = false)
	public Project getProject()
	{
		return this.project;
	}

	public void setProject(Project project)
	{
		this.project = project;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription()
	{
		return this.description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}

	@Column(name = "priority", nullable = false)
	public int getPriority()
	{
		return this.priority;
	}

	public void setPriority(int priority)
	{
		this.priority = priority;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_created", nullable = false, length = 19)
	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_modified", nullable = false, length = 19)
	public Date getDateModified()
	{
		return this.dateModified;
	}

	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

	@ManyToMany
	@JoinTable(name = "goal_asset", joinColumns = {@JoinColumn(name = "goal_id")}, inverseJoinColumns = {@JoinColumn(name = "asset_id")})
	public Set<Asset> getAssets()
	{
		return assets;
	}

	public void setAssets(Set<Asset> assets)
	{
		this.assets = assets;
	}

	public GwtSubGoal createSubGoal()
	{
		GwtSubGoal subGoal = new GwtSubGoal();
		subGoal.setId(this.id);
		subGoal.setDescription(this.description);
		subGoal.setPriority(this.priority);
		List<GwtAsset> assets = new ArrayList<GwtAsset>();
		for (Asset a : this.assets)
		{
			GwtAsset ga = a.createGwtAsset();
			assets.add(ga);
		}
		subGoal.setAssets(assets);
		return subGoal;
	}

	
	public String toString()
	{
		String toString = "goal id: " + this.id;
		return toString;
	}

}
