package edu.cmu.square.server.dao.model;

// Generated May 17, 2009 5:07:01 PM by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import edu.cmu.square.client.model.GwtInspectionTechnique;

/**
 * InspectionTechnique generated by hbm2java
 */
@Entity
@Table(name = "inspection_technique")
public class InspectionTechnique implements java.io.Serializable
{

	private static final long serialVersionUID = 3357171898153951476L;
	private Integer id;
	private String name;
	private String description;
	private Date dateCreated;
	private Date dateModified;
	private Project project;

	public InspectionTechnique()
	{
		
	}
	
	public InspectionTechnique(GwtInspectionTechnique gwtInspection)
	{
		this.id = gwtInspection.getInspectionTechniqueId();
		this.name = gwtInspection.getTitle();
		this.description = gwtInspection.getDescription();
	}

	public InspectionTechnique(String name, String description, Date dateCreated, Date dateModified)
	{
		this.name = name;
		this.description = description;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
	}

	public InspectionTechnique(String name, String description, Date dateCreated, Date dateModified, Project project)
	{
		this.name = name;
		this.description = description;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
		this.project = project;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription()
	{
		return this.description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_created", nullable = false, length = 19)
	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_modified", nullable = false, length = 19)
	public Date getDateModified()
	{
		return this.dateModified;
	}

	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pid", nullable = false)
	public Project getProject()
	{
		return this.project;
	}

	public void setProject(Project value)
	{
		this.project = value;
	}
	
	
	public GwtInspectionTechnique createGwtInspectionTechnique()
	{
		GwtInspectionTechnique target = new GwtInspectionTechnique();
		target.setTitle(this.name);
		target.setDescription(this.description);
		target.setInspectionTechniqueId(this.id);
		
		return target;
	}

}
