package edu.cmu.square.server.dao.model;

// Generated May 17, 2009 5:07:01 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProjectStepId generated by hbm2java
 */
@Embeddable
public class ProjectStepId implements java.io.Serializable {

	private static final long serialVersionUID = 3505128898548927536L;
	private int stepId;
	private int projectId;
	

	public ProjectStepId() {
	}

	

	@Column(name = "stepId", nullable = false)
	public int getStepId() {
		return this.stepId;
	}

	public void setStepId(int stepId) {
		this.stepId = stepId;
	}

	@Column(name = "projectId", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	

	

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProjectStepId))
			return false;
		ProjectStepId castOther = (ProjectStepId) other;

		return (this.getStepId() == castOther.getStepId())
				&& (this.getProjectId() == castOther.getProjectId());
				
				
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStepId();
		result = 37 * result + this.getProjectId();
		
		
		return result;
	}
	
	

}
