package edu.cmu.square.server.dao.model;

// Generated May 17, 2009 5:07:01 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserRequirementCategoryId generated by hbm2java
 */
@Embeddable
public class RequirementCategoryId implements java.io.Serializable {

	private static final long serialVersionUID = -186482848152200274L;
	private int rid;
	private int cid;

	public RequirementCategoryId() {
	}

	public RequirementCategoryId(int uid, int rid, int cid) {
		this.rid = rid;
		this.cid = cid;
	}

	
	@Column(name = "requirement_id", nullable = false)
	public int getRid() {
		return this.rid;
	}

	public void setRid(int rid) {
		this.rid = rid;
	}

	@Column(name = "category_id", nullable = false)
	public int getCid() {
		return this.cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RequirementCategoryId))
			return false;
		RequirementCategoryId castOther = (RequirementCategoryId) other;

		return ((this.getRid() == castOther.getRid())
				&& (this.getCid() == castOther.getCid()));
	}

	public int hashCode() {
		int result = 17;
		result = 37 * result + this.getRid();
		result = 37 * result + this.getCid();
		return result;
	}

}
