package edu.cmu.square.server.dao.model;

// Generated May 17, 2009 5:07:01 PM by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import edu.cmu.square.client.model.GwtRole;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role")
public class Role implements java.io.Serializable {
	 
	  
	private static final long serialVersionUID = -3551908313413631843L;
	private Integer id;
	private String name;
	private String description;
	private Date dateCreated;
	private Date dateModified;
	private Set<Project> projects = new HashSet<Project>();
	private Set<User> users = new HashSet<User>();
//	private Set<UserProjectRole> userProjectRoles = new HashSet<UserProjectRole>(
//			0);

	public Role() {
	}

	



	public Role(GwtRole gwtRole) {
		this.id = gwtRole.getId();
		this.name = gwtRole.getName();
		this.description = gwtRole.getDescription();
	}





	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false, length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_created", nullable = false, length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_modified", nullable = false, length = 19)
	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}
	@ManyToMany(
	        cascade = {CascadeType.PERSIST, CascadeType.MERGE},
	        mappedBy = "roles",
	        targetEntity = User.class
	    )
	public Set<User> getUsers() {
		return users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}
	@ManyToMany
	  @JoinTable(name = "user_project_role",
	    joinColumns = {
	      @JoinColumn(name="role_id")           
	    },
	    inverseJoinColumns = {
	      @JoinColumn(name="project_id")
	    }
	  )
	public Set<Project> getProjects() {
		return projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}
	
	public GwtRole createGwtRole() {
		GwtRole gwtRole = new GwtRole();
		gwtRole.setDescription(this.description);
		gwtRole.setName(this.name);
		gwtRole.setId(this.id);
		return gwtRole;
	}

	
	public String toString() {
		return this.name;
	}

	
}
