package edu.cmu.square.server.dao.model;

// Generated May 21, 2009 2:16:17 PM by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import edu.cmu.square.client.model.GwtStep;
import edu.cmu.square.client.model.StepStatus;

/**
 * Step generated by hbm2java
 */
@Entity
@Table(name = "step")
public class Step implements java.io.Serializable
{

	private static final long serialVersionUID = 4832789752331502631L;
	private Integer id;
	private String description;
	private boolean privacy;
	private boolean security;
	private Date dateCreated;
	private Date dateModified;
	private Set<ProjectStep> projectSteps = new HashSet<ProjectStep>(0);


	private Set<Project> projects;

	public Step()
		{
		}

	public Step(String description, String stakeholderResponsibilities, String requirementsEngineerResponisibilities, String exitCriteria,
			String websiteUse, String stepType, Date dateModified)
		{
			this.description = description;

			this.dateModified = dateModified;
		}

	public Step(String description, String stakeholderResponsibilities, String requirementsEngineerResponisibilities, String exitCriteria,
			String websiteUse, String stepType, Date dateCreated, Date dateModified)
		{
			this.description = description;
			this.dateCreated = dateCreated;
			this.dateModified = dateModified;

		}
	public GwtStep createGwtStep(int projectId)
	{

		GwtStep gwtStep = new GwtStep();
		gwtStep.setId(this.id);
		gwtStep.setDescription(this.description);
		gwtStep.setPrivacy(this.privacy);
		gwtStep.setSecurity(this.security);

		String status = "";

		for (ProjectStep ps : this.projectSteps)
		{
			if (ps.getProject() == null)
			{
				gwtStep.setStatus(StepStatus.NotStarted);
				break;
			}

			if (ps.getProject().getId().intValue() == projectId)
			{
				status = ps.getStatus();
				break;
			}

		}

		gwtStep.setStatus(StepStatus.convertLabel(status));

		return gwtStep;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription()
	{
		return this.description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_created", length = 19)
	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_modified", nullable = false, length = 19)
	public Date getDateModified()
	{
		return this.dateModified;
	}

	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "step")
	public Set<ProjectStep> getProjectSteps()
	{
		return this.projectSteps;
	}

	public void setProjectSteps(Set<ProjectStep> projectSteps)
	{
		this.projectSteps = projectSteps;
	}

	@Column(name = "privacy", nullable = false)
	public boolean isPrivacy()
	{
		return this.privacy;
	}

	public void setPrivacy(boolean privacy)
	{
		this.privacy = privacy;
	}

	@Column(name = "security", nullable = false)
	public boolean isSecurity()
	{
		return this.security;
	}

	public void setSecurity(boolean security)
	{
		this.security = security;
	}

	@ManyToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, mappedBy = "steps", targetEntity = Project.class)
	public Set<Project> getProjects()
	{
		return projects;
	}

	public void setProjects(Set<Project> projects)
	{
		this.projects = projects;
	}

}
