package edu.cmu.square.server.dao.model;

// Generated May 17, 2009 5:07:01 PM by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import edu.cmu.square.client.model.GwtTechnique;

/**
 * Technique generated by hbm2java
 */
@Entity
@Table(name = "technique")
public class Technique implements java.io.Serializable
{
	private static final long serialVersionUID = 2413737370254436865L;

	private Integer id;
	private String name;
	private String description;
	private boolean type;
	private Date dateCreated;
	private Date dateModified;
	private Project project;

	public Technique()
	{
	}

	public Technique(GwtTechnique gwtElicitTechnique)
	{
		this.id = gwtElicitTechnique.getTechniqueId();
		this.name = gwtElicitTechnique.getTitle();
		this.description = gwtElicitTechnique.getDescription();

		// The db uses a boolean to determine the type of the
		// technique. If it's a security technique, it's true, false otherwise.
		this.type = gwtElicitTechnique.isSecurityTechnique();
	}

	public Technique(String name, String description, boolean type, Date dateCreated, Date dateModified)
	{
		this.name = name;
		this.description = description;
		this.type = type;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "type", nullable = false)
	public boolean getType() {
		return this.type;
	}

	public void setType(boolean type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_created", nullable = false, length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_modified", nullable = false, length = 19)
	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}


	public GwtTechnique createGwtTechnique()
	{
		GwtTechnique newTechnique = new GwtTechnique();
		newTechnique.setTitle(this.name);
		newTechnique.setDescription(this.description);
		newTechnique.setTechniqueId(this.id);
		
		return newTechnique;
	}

	// @OneToMany(fetch = FetchType.LAZY, mappedBy = "securityTechnique")
	// public Set<Project> getProjectsForStid() {
	// return this.projectsForStid;
	// }
	//
	// public void setProjectsForStid(Set<Project> projectsForStid) {
	// this.projectsForStid = projectsForStid;
	// }
	//
	// @OneToMany(fetch = FetchType.LAZY, mappedBy = "privacyTechnique")
	// public Set<Project> getProjectsForPtid() {
	// return this.projectsForPtid;
	// }
	//
	// public void setProjectsForPtid(Set<Project> projectsForPtid) {
	// this.projectsForPtid = projectsForPtid;
	// }

}
