package edu.cmu.square.server.dao.model;

// Generated May 17, 2009 5:07:01 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TechniqueTechniqueEvaluationId generated by hbm2java
 */
@Embeddable
public class TechniqueTechniqueEvaluationId implements java.io.Serializable {

	private static final long serialVersionUID = -8075692555445089004L;
	private int tid;
	private int eid;
	private int pid;
	//private int value;

	public TechniqueTechniqueEvaluationId() {
	}

/*	public TechniqueTechniqueEvaluationId(int tid, int eid, int pid, int value) {
		this.tid = tid;
		this.eid = eid;
		this.pid = pid;
		this.value = value;
	}*/
	public TechniqueTechniqueEvaluationId(int tid, int eid, int pid) {
		this.tid = tid;
		this.eid = eid;
		this.pid = pid;
		
	}

	@Column(name = "technique_id", nullable = false)
	public int getTid() {
		return this.tid;
	}

	public void setTid(int tid) {
		this.tid = tid;
	}

	@Column(name = "evaluation_id", nullable = false)
	public int getEid() {
		return this.eid;
	}

	public void setEid(int eid) {
		this.eid = eid;
	}

	@Column(name = "pid", nullable = false)
	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}



	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TechniqueTechniqueEvaluationId))
			return false;
		TechniqueTechniqueEvaluationId castOther = (TechniqueTechniqueEvaluationId) other;

		return (this.getTid() == castOther.getTid())
				&& (this.getEid() == castOther.getEid())
				&& (this.getPid() == castOther.getPid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTid();
		result = 37 * result + this.getEid();
		result = 37 * result + this.getPid();
	
		return result;
	}

}
