package edu.cmu.square.server.dao.model;

// Generated May 17, 2009 5:07:01 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TechniqueTechniqueEvaluation generated by hbm2java
 */
@Entity
@Table(name = "technique_evaluation_criteria")
public class TechniqueEvaluationCriteria implements java.io.Serializable {

	private static final long serialVersionUID = -7623130633439780480L;
	private TechniqueTechniqueEvaluationId id;
	private Technique technique;
	private EvaluationCriteria techniqueEvaluation;
	private Project project;
	private int value;
	

	public TechniqueEvaluationCriteria() {
	}


	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "pid", column = @Column(name = "pid", nullable = false)),
			@AttributeOverride(name = "technique_id", column = @Column(name = "technique_id", nullable = false)),
			@AttributeOverride(name = "evaluation_id", column = @Column(name = "evaluation_id", nullable = false)),
			@AttributeOverride(name = "value", column = @Column(name = "value", nullable = false)) })
	public TechniqueTechniqueEvaluationId getId() {
		return this.id;
	}

	public void setId(TechniqueTechniqueEvaluationId id) {
		this.id = id;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pid", nullable = false, insertable = false, updatable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "technique_id", nullable = false, insertable = false, updatable = false)
	public Technique getTechnique() {
		return this.technique;
	}

	public void setTechnique(Technique technique) {
		this.technique = technique;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "evaluation_id", nullable = false, insertable = false, updatable = false)
	public EvaluationCriteria getTechniqueEvaluation() {
		return this.techniqueEvaluation;
	}

	public void setTechniqueEvaluation(EvaluationCriteria techniqueEvaluation) {
		this.techniqueEvaluation = techniqueEvaluation;
	}
	@Column(name = "value", nullable = false)
	public int getValue() {
		return this.value;
	}

	public void setValue(int value) {
		this.value = value;
	}
}
