package edu.cmu.square.server.dao.model;

// Generated May 17, 2009 5:07:01 PM by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import edu.cmu.square.client.model.GwtTerm;

/**
 * Term generated by hbm2java
 */
@Entity
@Table(name = "term")
public class Term implements java.io.Serializable {

	private static final long serialVersionUID = 166357024073794893L;
	private Integer id;
	private Project project;
	private String term;
	private String definition;
	
	private Date dateCreated;
	private Date dateModified;

	public Term() {
		
		
	}

	public Term(GwtTerm gwtTerm){
		this.id = gwtTerm.getId();
		this.definition = gwtTerm.getDefinition();
		this.term = gwtTerm.getTerm();
	}
	public Term(Project project, String term, String definition,
			 Date dateCreated, Date dateModified) {
		this.project = project;
		this.term = term;
		this.definition = definition;
		
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pid", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "term", nullable = false)
	public String getTerm() {
		return this.term;
	}

	public void setTerm(String term) {
		this.term = term;
	}

	@Column(name = "definition", nullable = false, length = 65535)
	public String getDefinition() {
		return this.definition;
	}

	public void setDefinition(String definition) {
		this.definition = definition;
	}



	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_created", nullable = false, length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_modified", nullable = false, length = 19)
	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}
	public void update(GwtTerm gwtTerm) {
		
		this.id = gwtTerm.getId();
		this.definition=gwtTerm.getDefinition();
		this.term = gwtTerm.getTerm();
		
	}
	public GwtTerm createGwtTerm() {
		
		GwtTerm gwtTerm = new GwtTerm();
		gwtTerm.setId(this.id);
		gwtTerm.setTerm(this.term);
		gwtTerm.setDefinition(this.definition);
		
		gwtTerm.setProjectId(this.project!=null?this.project.getId():null);
	
		return gwtTerm;
	}


}
