package edu.cmu.square.server.dao.model;

// Generated May 17, 2009 5:07:01 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserAhpId generated by hbm2java
 */
@Embeddable
public class UserAhpId implements java.io.Serializable {

	private static final long serialVersionUID = -7026563441481668542L;
	private int uid;
	private int ridA;
	private int ridB;

	public UserAhpId() {
	}

	public UserAhpId(int uid, int ridA, int costA, int valueA, int ridB,
			int costB, int valueB) {
		this.uid = uid;
		this.ridA = ridA;
		this.ridB = ridB;
		
	}

	@Column(name = "uid", nullable = false)
	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	@Column(name = "ridA", nullable = false)
	public int getRidA() {
		return this.ridA;
	}

	public void setRidA(int ridA) {
		this.ridA = ridA;
	}

	

	@Column(name = "ridB", nullable = false)
	public int getRidB() {
		return this.ridB;
	}

	public void setRidB(int ridB) {
		this.ridB = ridB;
	}

	

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserAhpId))
			return false;
		UserAhpId castOther = (UserAhpId) other;

		return (this.getUid() == castOther.getUid())
		
				&& ((this.getRidA() == castOther.getRidA())
				&& (this.getRidB() == castOther.getRidB())
				||((this.getRidA() == castOther.getRidB())
						&& (this.getRidB() == castOther.getRidA()))
				);
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUid();
		result = 37 * result + this.getRidA();
		result = 37 * result + this.getRidB();
		return result;
	}

}
