package edu.cmu.square.server.dao.model;

// Generated May 28, 2009 8:04:40 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserProjectRoleId generated by hbm2java
 */
@Embeddable
public class UserProjectRoleId implements java.io.Serializable {

	private static final long serialVersionUID = -3632742778690185684L;
	private int userId;
	private int projectId;
	private int roleId;

	public UserProjectRoleId() {
	}

	public UserProjectRoleId(int userId, int projectId, int roleId) {
		this.userId = userId;
		this.projectId = projectId;
		this.roleId = roleId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "project_id", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Column(name = "role_id", nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserProjectRoleId))
			return false;
		UserProjectRoleId castOther = (UserProjectRoleId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getProjectId() == castOther.getProjectId())
				&& (this.getRoleId() == castOther.getRoleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getProjectId();
		result = 37 * result + this.getRoleId();
		return result;
	}

}
